In [2]:
import matplotlib.pyplot as plt
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
import seaborn as sns
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import apriori


# Importing the dataset
dataset = pd.read_csv('Admission_Predict_Ver1.1.csv')
type(dataset)



for col in dataset.columns:
    print (col)


df=dataset.drop(dataset[dataset.Admit<=0.72].index)
df=df.drop(['Admit'],axis=1)
df.count()

Serial_No
GRE_Score
TOEFL_Score
University_Rating
SOP
LOR
CGPA
Research
Admit

Serial_No            248
GRE_Score            248
TOEFL_Score          248
University_Rating    248
SOP                  248
LOR                  248
CGPA                 248
Research             248
dtype: int64

In [3]:
for index,rows in df.iterrows():
    if df.loc[index,'Research']==1:
        df.loc[index,'Research']='Research-1'
    else:
        df.loc[index,'Research']='Research-0'




for index, row in df.iterrows():

    if df.loc[index,'GRE_Score'] >=320:
        df.loc[index,'GRE_Score']='GRE-1'
    elif df.loc[index,'GRE_Score']<300:
        df.loc[index,'GRE_Score']='GRE-3'
    else:
        df.loc[index,'GRE_Score']='GRE-2'



df.groupby('GRE_Score').count()



for index, row in df.iterrows():

    if df.loc[index,'TOEFL_Score'] >=110:
        df.loc[index,'TOEFL_Score']='TOEFL-1'
    elif df.loc[index,'TOEFL_Score']<100:
        df.loc[index,'TOEFL_Score']='TOEFL-3'
    else:
        df.loc[index,'TOEFL_Score']='TOEFL-2'

df.groupby('TOEFL_Score').count()


for index, row in df.iterrows():

    if df.loc[index,'SOP']==4.5:
        df.loc[index,'SOP']=5
    elif df.loc[index,'SOP']==3.5:
        df.loc[index,'SOP']=4
    elif df.loc[index,'SOP']==2.5:
        df.loc[index,'SOP']=3
    elif df.loc[index,'SOP']==1.5:
        df.loc[index,'SOP']=2
    elif df.loc[index,'SOP']==0.5:
        df.loc[index,'SOP']=1
    else:
        continue

df.groupby('SOP').count()

for index, row in df.iterrows():

    if df.loc[index,'LOR']==4.5:
        df.loc[index,'LOR']=5
    elif df.loc[index,'LOR']==3.5:
        df.loc[index,'LOR']=4
    elif df.loc[index,'LOR']==2.5:
        df.loc[index,'LOR']=3
    elif df.loc[index,'LOR']==1.5:
        df.loc[index,'LOR']=2
    elif df.loc[index,'LOR']==0.5:
        df.loc[index,'LOR']=1
    else:
        continue

df.groupby('LOR').count()



for index,rows in df.iterrows():
    if df.loc[index,'SOP']==5:
        df.loc[index,'SOP']='SOP-5'

    elif df.loc[index,'SOP']==4:
        df.loc[index,'SOP']='SOP-4'

    elif df.loc[index,'SOP']==3:
        df.loc[index,'SOP']='SOP-3'

    elif df.loc[index,'SOP']==2:
        df.loc[index,'SOP']='SOP-2'

    else:
        df.loc[index,'SOP']='SOP-1'


for index,rows in df.iterrows():
    if df.loc[index,'LOR']==5:
        df.loc[index,'LOR']='LOR-5'

    elif df.loc[index,'LOR']==4:
        df.loc[index,'LOR']='LOR-4'

    elif df.loc[index,'LOR']==3:
        df.loc[index,'LOR']='LOR-3'

    elif df.loc[index,'LOR']==2:
        df.loc[index,'LOR']='LOR-2'

    else:
        df.loc[index,'LOR']='LOR-1'



for index,rows in df.iterrows():
    if df.loc[index,'CGPA']>6.5 and df.loc[index,'CGPA']<=7.0:
        df.loc[index,'CGPA']='CGPA:6.5-7.0'
    elif df.loc[index,'CGPA']>7.0 and df.loc[index,'CGPA']<=7.5:
        df.loc[index,'CGPA']='CGPA:7.25-7.5'
    elif df.loc[index,'CGPA']>7.5 and df.loc[index,'CGPA']<=8.0:
        df.loc[index,'CGPA']='CGPA:7.5-8.0'
    elif df.loc[index,'CGPA']>8.0 and df.loc[index,'CGPA']<=8.5:
        df.loc[index,'CGPA']='CGPA:8.0-8.5'
    elif df.loc[index,'CGPA']>8.5 and df.loc[index,'CGPA']<=9.0:
        df.loc[index,'CGPA']='CPGA:8.5-9.0'
    elif df.loc[index,'CGPA']>9.0 and df.loc[index,'CGPA']<=9.5:
        df.loc[index,'CGPA']='CGPA:9.0-9.5'
    elif df.loc[index,'CGPA']>9.5:
        df.loc[index,'CGPA']='CGPA:9.5+'
    
    

df.to_csv('datafinal.csv',index=False)

In [4]:


datawith5=df.loc[(df.University_Rating==5)]
datawith5=datawith5.drop(['University_Rating'],axis=1)

datawith4=df.loc[(df.University_Rating==4)]

datawith4=datawith4.drop(['University_Rating'],axis=1)

datawith3=df.loc[(df.University_Rating==3)]

datawith3=datawith3.drop(['University_Rating'],axis=1)


datawith2=df.loc[(df.University_Rating==2)]

datawith2=datawith2.drop(['University_Rating'],axis=1)

datawith1=df.loc[(df.University_Rating==1)]

datawith1=datawith1.drop(['University_Rating'],axis=1)


datawith5.to_csv('data5.csv',index=False)
datawith4.to_csv('data4.csv',index=False)
datawith3.to_csv('data3.csv',index=False)
datawith2.to_csv('data2.csv',index=False)
datawith1.to_csv('data1.csv',index=False)

In [5]:
data=pd.read_csv('data5.csv')

In [6]:
data.count()

Serial_No      68
GRE_Score      68
TOEFL_Score    68
SOP            68
LOR            68
CGPA           68
Research       68
dtype: int64

In [7]:
records = []
for i in range(0,len(data)):
    records.append([str(data.values[i,j]) for j in range(1,7)])

records=records[1:len(data)]

te = TransactionEncoder()
te_ary = te.fit(records).transform(records)
df5 = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = apriori(df5, min_support=0.50, use_colnames=True)

frequent_itemsets=frequent_itemsets.sort_values(by='support',ascending=0)

frequent_itemsets

     support                                    itemsets
1   0.970149                                     (GRE-1)
3   0.925373                                (Research-1)
10  0.910448                         (GRE-1, Research-1)
5   0.895522                                   (TOEFL-1)
12  0.895522                            (TOEFL-1, GRE-1)
24  0.850746                (TOEFL-1, GRE-1, Research-1)
16  0.850746                       (TOEFL-1, Research-1)
4   0.701493                                     (SOP-5)
11  0.686567                              (GRE-1, SOP-5)
2   0.671642                                     (LOR-5)
14  0.641791                            (TOEFL-1, LOR-5)
23  0.641791                  (GRE-1, Research-1, SOP-5)
25  0.641791                     (TOEFL-1, GRE-1, SOP-5)
17  0.641791                            (TOEFL-1, SOP-5)
15  0.641791                         (Research-1, SOP-5)
13  0.641791                         (Research-1, LOR-5)
22  0.641791                     (TOEFL-1, GRE-1, LOR-5)
9   0.641791                              (GRE-1, LOR-5)
26  0.626866                (TOEFL-1, Research-1, LOR-5)
29  0.626866         (TOEFL-1, GRE-1, Research-1, LOR-5)
21  0.626866                  (GRE-1, Research-1, LOR-5)
27  0.611940                (TOEFL-1, Research-1, SOP-5)
30  0.611940         (TOEFL-1, GRE-1, Research-1, SOP-5)
18  0.582090           (GRE-1, Research-1, CGPA:9.0-9.5)
7   0.582090                  (Research-1, CGPA:9.0-9.5)
6   0.582090                       (GRE-1, CGPA:9.0-9.5)
0   0.582090                              (CGPA:9.0-9.5)
20  0.552239         (TOEFL-1, Research-1, CGPA:9.0-9.5)
19  0.552239              (TOEFL-1, GRE-1, CGPA:9.0-9.5)
8   0.552239                     (TOEFL-1, CGPA:9.0-9.5)
28  0.552239  (TOEFL-1, GRE-1, Research-1, CGPA:9.0-9.5)

In [8]:
records

[['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-4', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-2', 'SOP-5', 'LOR-4', 'CPGA:8.5-9.0', 'Research-0'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-4', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.5+', 'Research-0'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-2', 'TOEFL-2', 'SOP-5', 'LOR-5', 'CPGA:8.5-9.0', 'Research-0'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CPGA:8.5-9.0', 'Research-0'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CPGA:8.5-9.0', 'Research-0'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CPGA:8.5-9.0', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CPGA:8.5-9.0', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-2', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-2', 'SOP-4', 'LOR-4', 'CPGA:8.5-9.0', 'Research-1'],
 ['GRE-1', 'TOEFL-2', 'SOP-4', 'LOR-4', 'CPGA:8.5-9.0', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-2', 'TOEFL-2', 'SOP-4', 'LOR-5', 'CPGA:8.5-9.0', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-4', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-2', 'SOP-5', 'LOR-4', 'CGPA:9.0-9.5', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1'],
 ['GRE-1', 'TOEFL-1', 'SOP-5', 'LOR-5', 'CGPA:9.5+', 'Research-1']]

In [9]:
df5

,CGPA:9.0-9.5,CGPA:9.5+,CPGA:8.5-9.0,GRE-1,GRE-2,LOR-4,LOR-5,Research-0,Research-1,SOP-4,SOP-5,TOEFL-1,TOEFL-2
0,True,False,False,True,False,False,True,False,True,False,True,True,False
1,False,True,False,True,False,False,True,False,True,False,True,True,False
2,False,True,False,True,False,True,False,False,True,True,False,True,False
3,False,True,False,True,False,False,True,False,True,False,True,True,False
4,False,False,True,True,False,True,False,True,False,False,True,False,True
5,False,True,False,True,False,True,False,False,True,True,False,True,False
6,False,True,False,True,False,False,True,False,True,True,False,True,False
7,True,False,False,True,False,False,True,False,True,False,True,True,False
8,True,False,False,True,False,True,False,False,True,False,True,True,False
9,True,False,False,True,False,True,False,False,True,False,True,True,False
10,True,False,False,True,False,False,True,False,True,True,False,True,False
11,False,True,False,True,False,True,False,True,False,False,True,True,False
12,False,True,False,True,False,False,True,False,True,False,True,True,False
13,False,True,False,True,False,False,True,False,True,False,True,True,False
14,True,False,False,True,False,False,True,False,True,False,True,True,False
15,True,False,False,True,False,False,True,False,True,False,True,True,False
16,True,False,False,True,False,False,True,False,True,True,False,True,False
17,True,False,False,True,False,False,True,False,True,False,True,True,False
18,True,False,False,True,False,False,True,False,True,False,True,True,False
19,False,True,False,True,False,False,True,False,True,False,True,True,False
20,True,False,False,True,False,False,True,False,True,False,True,True,False
21,True,False,False,True,False,False,True,False,True,False,True,True,False
22,False,True,False,True,False,False,True,False,True,True,False,True,False
23,False,False,True,False,True,False,True,True,False,False,True,False,True
24,False,False,True,True,False,False,True,True,False,True,False,True,False
25,True,False,False,True,False,True,False,False,True,True,False,True,False
26,True,False,False,True,False,True,False,False,True,True,False,True,False
27,True,False,False,True,False,False,True,False,True,False,True,True,False
28,True,False,False,True,False,False,True,False,True,False,True,True,False
29,False,False,True,True,False,True,False,True,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,False,True,False,True,False,False,True,False,True,False,True,True,False
38,False,True,False,True,False,False,True,False,True,False,True,True,False
39,False,True,False,True,False,False,True,False,True,True,False,True,False
40,False,True,False,True,False,False,True,False,True,False,True,True,False
41,True,False,False,True,False,False,True,False,True,False,True,True,False
42,True,False,False,True,False,True,False,False,True,False,True,True,False
43,True,False,False,True,False,True,False,False,True,False,True,True,False
44,True,False,False,True,False,False,True,False,True,False,True,True,False
45,True,False,False,True,False,True,False,False,True,False,True,False,True
46,True,False,False,True,False,False,True,False,True,False,True,True,False
47,True,False,False,True,False,True,False,False,True,True,False,True,False
48,True,False,False,True,False,True,False,False,True,False,True,True,False
49,True,False,False,True,False,False,True,False,True,False,True,True,False
50,True,False,False,True,False,False,True,False,True,False,True,True,False
51,False,False,True,True,False,True,False,False,True,True,False,False,True
52,False,False,True,True,False,True,False,False,True,True,False,False,True
53,True,False,False,True,False,False,True,False,True,False,True,True,False
54,False,True,False,True,False,False,True,False,True,False,True,True,False
55,False,True,False,True,False,False,True,False,True,False,True,True,False
56,True,False,False,True,False,False,True,False,True,True,False,True,False
57,False,True,False,True,False,False,True,False,True,True,False,True,False
58,True,False,False,True,False,False,True,False,True,False,True,True,False
59,True,False,False,True,False,False,True,False,True,False,True,True,False
60,True,False,False,True,False,False,True,False,True,True,False,True,False
61,True,False,False,True,False,False,True,False,True,False,True,True,False
62,False,False,True,False,True,False,True,False,True,True,False,False,True
63,True,False,False,True,False,True,False,False,True,True,False,True,False
64,True,False,False,True,False,True,False,False,True,False,True,False,True
65,False,True,False,True,False,False,True,False,True,False,True,True,False
66,False,True,False,True,False,False,True,False,True,False,True,True,False

In [10]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
rules=rules.sort_values(by="confidence",ascending=0)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
95,(CGPA:9.0-9.5),(Research-1),0.582090,0.925373,0.582090,1.000000,1.080645,0.043440,inf
18,"(Research-1, SOP-5)",(GRE-1),0.641791,0.970149,0.641791,1.000000,1.030769,0.019158,inf
36,"(GRE-1, LOR-5)",(TOEFL-1),0.641791,0.895522,0.641791,1.000000,1.116667,0.067053,inf
35,"(TOEFL-1, LOR-5)",(GRE-1),0.641791,0.970149,0.641791,1.000000,1.030769,0.019158,inf
76,"(TOEFL-1, Research-1, SOP-5)",(GRE-1),0.611940,0.970149,0.611940,1.000000,1.030769,0.018267,inf
89,"(GRE-1, CGPA:9.0-9.5)",(Research-1),0.582090,0.925373,0.582090,1.000000,1.080645,0.043440,inf
90,"(Research-1, CGPA:9.0-9.5)",(GRE-1),0.582090,0.970149,0.582090,1.000000,1.030769,0.017376,inf
93,(CGPA:9.0-9.5),"(GRE-1, Research-1)",0.582090,0.910448,0.582090,1.000000,1.098361,0.052127,inf
51,"(GRE-1, Research-1, LOR-5)",(TOEFL-1),0.626866,0.895522,0.626866,1.000000,1.116667,0.065493,inf
97,(CGPA:9.0-9.5),(GRE-1),0.582090,0.970149,0.582090,1.000000,1.030769,0.017376,inf
23,"(TOEFL-1, SOP-5)",(GRE-1),0.641791,0.970149,0.641791,1.000000,1.030769,0.019158,inf
99,"(TOEFL-1, CGPA:9.0-9.5)",(Research-1),0.552239,0.925373,0.552239,1.000000,1.080645,0.041212,inf
104,"(TOEFL-1, CGPA:9.0-9.5)",(GRE-1),0.552239,0.970149,0.552239,1.000000,1.030769,0.016485,inf
50,"(TOEFL-1, Research-1, LOR-5)",(GRE-1),0.626866,0.970149,0.626866,1.000000,1.030769,0.018712,inf
5,"(TOEFL-1, Research-1)",(GRE-1),0.850746,0.970149,0.850746,1.000000,1.030769,0.025395,inf
2,(TOEFL-1),(GRE-1),0.895522,0.970149,0.895522,1.000000,1.030769,0.026732,inf
111,"(TOEFL-1, GRE-1, CGPA:9.0-9.5)",(Research-1),0.552239,0.925373,0.552239,1.000000,1.080645,0.041212,inf
112,"(TOEFL-1, Research-1, CGPA:9.0-9.5)",(GRE-1),0.552239,0.970149,0.552239,1.000000,1.030769,0.016485,inf
116,"(TOEFL-1, CGPA:9.0-9.5)","(GRE-1, Research-1)",0.552239,0.910448,0.552239,1.000000,1.098361,0.049454,inf
1,(Research-1),(GRE-1),0.925373,0.970149,0.910448,0.983871,1.014144,0.012698,1.850746
13,(SOP-5),(GRE-1),0.701493,0.970149,0.686567,0.978723,1.008838,0.006015,1.402985
43,"(TOEFL-1, LOR-5)",(Research-1),0.641791,0.925373,0.626866,0.976744,1.055514,0.032969,3.208955
63,"(GRE-1, LOR-5)",(Research-1),0.641791,0.925373,0.626866,0.976744,1.055514,0.032969,3.208955
44,"(Research-1, LOR-5)",(TOEFL-1),0.641791,0.895522,0.626866,0.976744,1.090698,0.052127,4.492537
64,"(Research-1, LOR-5)",(GRE-1),0.641791,0.970149,0.626866,0.976744,1.006798,0.004233,1.283582
57,"(Research-1, LOR-5)","(TOEFL-1, GRE-1)",0.641791,0.895522,0.626866,0.976744,1.090698,0.052127,4.492537
56,"(GRE-1, LOR-5)","(TOEFL-1, Research-1)",0.641791,0.850746,0.626866,0.976744,1.148103,0.080864,6.417910
54,"(TOEFL-1, LOR-5)","(GRE-1, Research-1)",0.641791,0.910448,0.626866,0.976744,1.072817,0.042548,3.850746
49,"(TOEFL-1, GRE-1, LOR-5)",(Research-1),0.641791,0.925373,0.626866,0.976744,1.055514,0.032969,3.208955
15,(LOR-5),(TOEFL-1),0.671642,0.895522,0.641791,0.955556,1.067037,0.040321,2.350746
...,...,...,...,...,...,...,...,...,...
84,(TOEFL-1),"(GRE-1, Research-1, SOP-5)",0.895522,0.641791,0.611940,0.683333,1.064729,0.037202,1.131186
78,"(TOEFL-1, GRE-1)","(Research-1, SOP-5)",0.895522,0.641791,0.611940,0.683333,1.064729,0.037202,1.131186
46,(Research-1),"(TOEFL-1, LOR-5)",0.925373,0.641791,0.626866,0.677419,1.055514,0.032969,1.110448
66,(Research-1),"(GRE-1, LOR-5)",0.925373,0.641791,0.626866,0.677419,1.055514,0.032969,1.110448
60,(Research-1),"(TOEFL-1, GRE-1, LOR-5)",0.925373,0.641791,0.626866,0.677419,1.055514,0.032969,1.110448
81,"(GRE-1, Research-1)","(TOEFL-1, SOP-5)",0.910448,0.641791,0.611940,0.672131,1.047274,0.027623,1.092537
19,(GRE-1),"(Research-1, SOP-5)",0.970149,0.641791,0.641791,0.661538,1.030769,0.019158,1.058345
38,(GRE-1),"(TOEFL-1, LOR-5)",0.970149,0.641791,0.641791,0.661538,1.030769,0.019158,1.058345
26,(GRE-1),"(TOEFL-1, SOP-5)",0.970149,0.641791,0.641791,0.661538,1.030769,0.019158,1.058345
40,(GRE-1),(LOR-5),0.970149,0.671642,0.641791,0.661538,0.984957,-0.009802,0.970149
86,(Research-1),"(TOEFL-1, GRE-1, SOP-5)",0.925373,0.641791,0.611940,0.661290,1.030383,0.018044,1.057569
72,(Research-1),"(TOEFL-1, SOP-5)",0.925373,0.641791,0.611940,0.661290,1.030383,0.018044,1.057569
115,"(TOEFL-1, Research-1)","(GRE-1, CGPA:9.0-9.5)",0.850746,0.582090,0.552239,0.649123,1.115160,0.057028,1.191045
110,"(TOEFL-1, GRE-1, Research-1)",(CGPA:9.0-9.5),0.850746,0.582090,0.552239,0.649123,1.115160,0.057028,1.191045
98,"(TOEFL-1, Research-1)",(CGPA:9.0-9.5),0.850746,0.582090,0.552239,0.649123,1.115160,0.057028,1.191045
65,(GRE-1),"(Research-1, LOR-5)",0.970149,0.641791,0.626866,0.646154,1.006798,0.004233,1.012330
59,(GRE-1),"(TOEFL-1, Research-1, LOR-5)",0.970149,0.626866,0.626866,0.646154,1.030769,0.018712,1.054510
88,"(GRE-1, Research-1)",(CGPA:9.0-9.5),0.910448,0.582090,0.582090,0.639344,1.098361,0.052127,1.158752
85,(GRE-1),"(TOEFL-1, Research-1, SOP-5)",0.970149,0.611940,0.611940,0.630769,1.030769,0.018267,1.050995
94,(Research-1),(CGPA:9.0-9.5),0.925373,0.582090,0.582090,0.629032,1.080645,0.043440,1.126541
92,(Research-1),"(GRE-1, CGPA:9.0-9.5)",0.925373,0.582090,0.582090,0.629032,1.080645,0.043440,1.126541
108,(TOEFL-1),(CGPA:9.0-9.5),0.895522,0.582090,0.552239,0.616667,1.059402,0.030965,1.090201
106,(TOEFL-1),"(GRE-1, CGPA:9.0-9.5)",0.895522,0.582090,0.552239,0.616667,1.059402,0.030965,1.090201
101,(TOEFL-1),"(Research-1, CGPA:9.0-9.5)",0.895522,0.582090,0.552239,0.616667,1.059402,0.030965,1.090201
114,"(TOEFL-1, GRE-1)","(Research-1, CGPA:9.0-9.5)",0.895522,0.582090,0.552239,0.616667,1.059402,0.030965,1.090201
103,"(TOEFL-1, GRE-1)",(CGPA:9.0-9.5),0.895522,0.582090,0.552239,0.616667,1.059402,0.030965,1.090201
120,(TOEFL-1),"(GRE-1, Research-1, CGPA:9.0-9.5)",0.895522,0.582090,0.552239,0.616667,1.059402,0.030965,1.090201
117,"(GRE-1, Research-1)","(TOEFL-1, CGPA:9.0-9.5)",0.910448,0.552239,0.552239,0.606557,1.098361,0.049454,1.138060
91,(GRE-1),"(Research-1, CGPA:9.0-9.5)",0.970149,0.582090,0.582090,0.600000,1.030769,0.017376,1.044776
96,(GRE-1),(CGPA:9.0-9.5),0.970149,0.582090,0.582090,0.600000,1.030769,0.017376,1.044776

In [11]:
data

    Serial_No GRE_Score TOEFL_Score    SOP    LOR          CGPA    Research
0           6     GRE-1     TOEFL-1  SOP-5  LOR-3  CGPA:9.0-9.5  Research-1
1          23     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
2          24     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
3          25     GRE-1     TOEFL-1  SOP-4  LOR-4     CGPA:9.5+  Research-1
4          26     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
5          27     GRE-1     TOEFL-2  SOP-5  LOR-4  CPGA:8.5-9.0  Research-0
6          34     GRE-1     TOEFL-1  SOP-4  LOR-4     CGPA:9.5+  Research-1
7          35     GRE-1     TOEFL-1  SOP-4  LOR-5     CGPA:9.5+  Research-1
8          36     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
9          45     GRE-1     TOEFL-1  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
10         46     GRE-1     TOEFL-1  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
11         47     GRE-1     TOEFL-1  SOP-4  LOR-5  CGPA:9.0-9.5  Research-1
12         48     GRE-1     TOEFL-1  SOP-5  LOR-4     CGPA:9.5+  Research-0
13         71     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
14         72     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
15         73     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
16         83     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
17         84     GRE-1     TOEFL-1  SOP-4  LOR-5  CGPA:9.0-9.5  Research-1
18         85     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
19        109     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
20        121     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
21        122     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
22        130     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
23        131     GRE-1     TOEFL-1  SOP-4  LOR-5     CGPA:9.5+  Research-1
24        132     GRE-2     TOEFL-2  SOP-5  LOR-5  CPGA:8.5-9.0  Research-0
25        134     GRE-1     TOEFL-1  SOP-4  LOR-5  CPGA:8.5-9.0  Research-0
26        135     GRE-1     TOEFL-1  SOP-4  LOR-4  CGPA:9.0-9.5  Research-1
27        143     GRE-1     TOEFL-1  SOP-4  LOR-4  CGPA:9.0-9.5  Research-1
28        152     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
29        153     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
..        ...       ...         ...    ...    ...           ...         ...
38        194     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
39        203     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
40        204     GRE-1     TOEFL-1  SOP-4  LOR-5     CGPA:9.5+  Research-1
41        214     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
42        216     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
43        235     GRE-1     TOEFL-1  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
44        236     GRE-1     TOEFL-1  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
45        238     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
46        261     GRE-1     TOEFL-2  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
47        277     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
48        286     GRE-1     TOEFL-1  SOP-4  LOR-4  CGPA:9.0-9.5  Research-1
49        287     GRE-1     TOEFL-1  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
50        288     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
51        338     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
52        339     GRE-1     TOEFL-2  SOP-4  LOR-4  CPGA:8.5-9.0  Research-1
53        340     GRE-1     TOEFL-2  SOP-4  LOR-4  CPGA:8.5-9.0  Research-1
54        363     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
55        386     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
56        424     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
57        425     GRE-1     TOEFL-1  SOP-4  LOR-5  CGPA:9.0-9.5  Research-1
58        426     GRE-1     TOEFL-1  SOP-4  LOR-5     CGPA:9.5+  Research-1
59        430     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
60        444     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
61        445     GRE-1     TOEFL-1  SOP-4  LOR-5  CGPA:9.0-9.5  Research-1
62        446     GRE-1     TOEFL-1  SOP-5  LOR-5  CGPA:9.0-9.5  Research-1
63        468     GRE-2     TOEFL-2  SOP-4  LOR-5  CPGA:8.5-9.0  Research-1
64        471     GRE-1     TOEFL-1  SOP-4  LOR-4  CGPA:9.0-9.5  Research-1
65        496     GRE-1     TOEFL-2  SOP-5  LOR-4  CGPA:9.0-9.5  Research-1
66        497     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1
67        498     GRE-1     TOEFL-1  SOP-5  LOR-5     CGPA:9.5+  Research-1

[68 rows x 7 columns]